package main

import (
	"encoding/json"
	"errors"
	"io"
	"os"
	"path/filepath"
	"sync"
	"time"
)

// Sentinel errors returned by FileStore.
var (
	ErrNotFound = errors.New("file not found")
	ErrExpired  = errors.New("file has expired")
)

// cleanupInterval controls how often the background goroutine scans for and
// removes expired files.
const cleanupInterval = 5 * time.Minute

// FileMeta holds metadata about an uploaded file.
type FileMeta struct {
	ID          string    `json:"id"`
	OrigName    string    `json:"orig_name"`
	ContentType string    `json:"content_type"`
	Size        int64     `json:"size"`
	UploadedAt  time.Time `json:"uploaded_at"`
	ExpiresAt   time.Time `json:"expires_at"`
	// StorageDir is the server-controlled absolute path to the storage directory.
	// It is persisted in meta.json so the index can be rebuilt on restart.
	StorageDir string `json:"storage_dir"`
}

// FileStore manages storage and retrieval of uploaded files on disk.
// It maintains an in-memory index that maps public file IDs (user-provided on
// download/info requests) to absolute directory paths that are controlled
// entirely by the server.  Filesystem paths are therefore never derived from
// user input, preventing path-traversal attacks.
type FileStore struct {
	dir   string
	ttl   time.Duration
	mu    sync.RWMutex
	index map[string]string // public ID -> absolute storage directory
}

// NewFileStore creates and initialises a FileStore that persists files to dir.
// It rebuilds the in-memory index by scanning existing entries so that files
// survive a server restart.  A background goroutine removes expired files.
func NewFileStore(dir string, ttl time.Duration) (*FileStore, error) {
	absDir, err := filepath.Abs(dir)
	if err != nil {
		return nil, err
	}
	if err := os.MkdirAll(absDir, 0o750); err != nil {
		return nil, err
	}
	fs := &FileStore{
		dir:   absDir,
		ttl:   ttl,
		index: make(map[string]string),
	}
	fs.rebuildIndex()
	go fs.cleanupLoop()
	return fs, nil
}

// Save writes the file content and its metadata to disk and registers the
// entry in the in-memory index.
func (fs *FileStore) Save(meta *FileMeta, r io.Reader) error {
	fs.mu.Lock()
	defer fs.mu.Unlock()

	// The storage directory is a server-controlled absolute path derived from
	// fs.dir (trusted) and meta.ID which has already been generated by the
	// server using crypto/rand. We store it in meta so it can be recovered
	// after a restart without ever deriving it from user input again.
	storageDir := filepath.Join(fs.dir, meta.ID)
	meta.StorageDir = storageDir

	if err := os.MkdirAll(storageDir, 0o750); err != nil {
		return err
	}

	// Write file data.
	dataPath := filepath.Join(storageDir, "data")
	f, err := os.OpenFile(dataPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o640)
	if err != nil {
		return err
	}
	n, err := io.Copy(f, r)
	f.Close()
	if err != nil {
		os.RemoveAll(storageDir)
		return err
	}
	// Update size from actual bytes written if header reported zero.
	if meta.Size == 0 {
		meta.Size = n
	}

	// Write metadata.
	metaPath := filepath.Join(storageDir, "meta.json")
	mf, err := os.OpenFile(metaPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC, 0o640)
	if err != nil {
		os.RemoveAll(storageDir)
		return err
	}
	err = json.NewEncoder(mf).Encode(meta)
	mf.Close()
	if err != nil {
		os.RemoveAll(storageDir)
		return err
	}

	// Register in the in-memory index.
	fs.index[meta.ID] = storageDir
	return nil
}

// Meta loads and returns the metadata for the given file ID.
func (fs *FileStore) Meta(id string) (*FileMeta, error) {
	fs.mu.RLock()
	defer fs.mu.RUnlock()
	return fs.loadMeta(id)
}

// Get returns the metadata and a ReadCloser for the file content.
// The caller must close the returned ReadCloser.
func (fs *FileStore) Get(id string) (*FileMeta, io.ReadCloser, error) {
	fs.mu.RLock()
	defer fs.mu.RUnlock()

	meta, err := fs.loadMeta(id)
	if err != nil {
		return nil, nil, err
	}

	// meta.StorageDir is a server-controlled path recovered from meta.json; it
	// is not derived from the user-provided id at this point.
	dataPath := filepath.Join(meta.StorageDir, "data")
	f, err := os.Open(dataPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil, ErrNotFound
		}
		return nil, nil, err
	}
	return meta, f, nil
}

// cleanupLoop periodically removes expired files.
func (fs *FileStore) cleanupLoop() {
	ticker := time.NewTicker(cleanupInterval)
	defer ticker.Stop()
	for range ticker.C {
		fs.deleteExpired()
	}
}

func (fs *FileStore) deleteExpired() {
	fs.mu.Lock()
	defer fs.mu.Unlock()

	now := time.Now().UTC()
	for id, storageDir := range fs.index {
		meta, err := fs.loadMetaFromDir(storageDir)
		if err != nil || now.After(meta.ExpiresAt) {
			os.RemoveAll(storageDir)
			delete(fs.index, id)
		}
	}
}

// loadMeta looks up the storage directory from the trusted index and reads
// metadata from it.  The user-provided id is only used as a map key; the
// resulting filesystem path comes from the server-controlled index value.
func (fs *FileStore) loadMeta(id string) (*FileMeta, error) {
	if !isValidID(id) {
		return nil, ErrNotFound
	}
	// Look up the server-controlled path from the index.
	storageDir, ok := fs.index[id]
	if !ok {
		return nil, ErrNotFound
	}
	return fs.loadMetaFromDir(storageDir)
}

// loadMetaFromDir reads and parses meta.json from a server-controlled
// absolute directory path.
func (fs *FileStore) loadMetaFromDir(storageDir string) (*FileMeta, error) {
	metaPath := filepath.Join(storageDir, "meta.json")
	f, err := os.Open(metaPath)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, ErrNotFound
		}
		return nil, err
	}
	defer f.Close()

	var meta FileMeta
	if err := json.NewDecoder(f).Decode(&meta); err != nil {
		return nil, err
	}

	if time.Now().UTC().After(meta.ExpiresAt) {
		return nil, ErrExpired
	}

	return &meta, nil
}

// rebuildIndex scans the uploads directory and reconstructs the in-memory
// index from persisted meta.json files.  Called once during initialisation.
func (fs *FileStore) rebuildIndex() {
	entries, err := os.ReadDir(fs.dir)
	if err != nil {
		return
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		storageDir := filepath.Join(fs.dir, entry.Name())
		metaPath := filepath.Join(storageDir, "meta.json")
		f, err := os.Open(metaPath)
		if err != nil {
			continue
		}
		var meta FileMeta
		err = json.NewDecoder(f).Decode(&meta)
		f.Close()
		if err != nil || meta.ID == "" || !isValidID(meta.ID) {
			continue
		}
		fs.index[meta.ID] = storageDir
	}
}

// isValidID checks that the id is a 32-character lowercase hex string.
func isValidID(id string) bool {
	if len(id) != 32 {
		return false
	}
	for _, c := range id {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}

